call czysc.cmd PLIKI xxx_01
call czysc.cmd PLIKI xxx_02
call czysc.cmd PLIKI xxx_03
call czysc.cmd PLIKI xxx_04
call czysc.cmd PLIKI xxx_05
call czysc.cmd PLIKI xxx_06
call czysc.cmd PLIKI xxx_07
call czysc.cmd PLIKI xxx_08
call czysc.cmd PLIKI xxx_09
call czysc.cmd PLIKI xxx_10
call czysc.cmd PLIKI xxx_11
call czysc.cmd PLIKI xxx_12
call czysc.cmd PLIKI xxx_13
call czysc.cmd PLIKI xxx_14
call czysc.cmd PLIKI xxx_15
call czysc.cmd PLIKI xxx_16
call czysc.cmd PLIKI xxx_17
call czysc.cmd PLIKI xxx_18
call czysc.cmd PLIKI xxx_19
call czysc.cmd PLIKI xxx_20
call czysc.cmd PLIKI xxx_21
call czysc.cmd PLIKI xxx_22
call czysc.cmd PLIKI xxx_23
call czysc.cmd PLIKI xxx_24
call czysc.cmd PLIKI xxx_25
call czysc.cmd PLIKI xxx_26
call czysc.cmd PLIKI xxx_27
call czysc.cmd PLIKI xxx_28
call czysc.cmd PLIKI xxx_29
call czysc.cmd PLIKI xxx_30
call czysc.cmd PLIKI xxx_31
call czysc.cmd PLIKI xxx_32
call czysc.cmd PLIKI xxx_33
call czysc.cmd PLIKI xxx_34
call czysc.cmd PLIKI xxx_35
call czysc.cmd PLIKI xxx_36
call czysc.cmd PLIKI xxx_37
call czysc.cmd PLIKI xxx_38
call czysc.cmd PLIKI xxx_39
call czysc.cmd PLIKI xxx_40
