call czysc.cmd WSZYSTKO xxx_01
call czysc.cmd WSZYSTKO xxx_02
call czysc.cmd WSZYSTKO xxx_03
call czysc.cmd WSZYSTKO xxx_04
call czysc.cmd WSZYSTKO xxx_05
call czysc.cmd WSZYSTKO xxx_06
call czysc.cmd WSZYSTKO xxx_07
call czysc.cmd WSZYSTKO xxx_08
call czysc.cmd WSZYSTKO xxx_09
call czysc.cmd WSZYSTKO xxx_10
call czysc.cmd WSZYSTKO xxx_11
call czysc.cmd WSZYSTKO xxx_12
call czysc.cmd WSZYSTKO xxx_13
call czysc.cmd WSZYSTKO xxx_14
call czysc.cmd WSZYSTKO xxx_15
call czysc.cmd WSZYSTKO xxx_16
call czysc.cmd WSZYSTKO xxx_17
call czysc.cmd WSZYSTKO xxx_18
call czysc.cmd WSZYSTKO xxx_19
call czysc.cmd WSZYSTKO xxx_20
call czysc.cmd WSZYSTKO xxx_21
call czysc.cmd WSZYSTKO xxx_22
call czysc.cmd WSZYSTKO xxx_23
call czysc.cmd WSZYSTKO xxx_24
call czysc.cmd WSZYSTKO xxx_25
call czysc.cmd WSZYSTKO xxx_26
call czysc.cmd WSZYSTKO xxx_27
call czysc.cmd WSZYSTKO xxx_28
call czysc.cmd WSZYSTKO xxx_29
call czysc.cmd WSZYSTKO xxx_30
call czysc.cmd WSZYSTKO xxx_31
call czysc.cmd WSZYSTKO xxx_32
call czysc.cmd WSZYSTKO xxx_33
call czysc.cmd WSZYSTKO xxx_34
call czysc.cmd WSZYSTKO xxx_35
call czysc.cmd WSZYSTKO xxx_36
call czysc.cmd WSZYSTKO xxx_37
call czysc.cmd WSZYSTKO xxx_38
call czysc.cmd WSZYSTKO xxx_39
call czysc.cmd WSZYSTKO xxx_40
